---
abstract: 'Working with Google GSuite services from the Request Tracker'
author:
  - 'Igor Derkach <gosha753951@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-GSuite
no_index:
  directory:
    - inc
requires:
  perl: 5.8.3
  Furl: 3.0.7
  Data::Validator: 1.07
  Mojo::Collection: 0
  Mojo::JWT::Google: 0
  JSON: 2.90
  Sub::Retry: 0.06
  Mouse: 0
  URI::Escape: 0
resources:
  license: http://dev.perl.org/licenses/
version: '0.1'
x_module_install_rtx_version: '0.36'
x_requires_rt: 4.0.0
